export const periodicTable = [
    {
        name: 'Hydrogen', 
        color: '#63b9d5', 
        atomicNumber: 1,
        symbol: 'H',
        relativeMass: 1.00794,
        protons: 1,
        neutrons: 0,
        electrons: 1,
    },
    {
        name: 'Helium',
        color: '#d1c991',
        atomicNumber: 2,
        symbol: 'He',
        relativeMass: 4.002602,
        protons: 2,
        neutrons: 2,
        electrons: 2,
    },
    {
        name: 'Lithium',
        color: '#4c6168',
        atomicNumber: 3,
        symbol: 'Li',
        relativeMass: 6.941,
        protons: 3,
        neutrons: 4,
        electrons: 3,
    },
        {
        name: 'Beryllium',
        color: '#c8c8c8',
        atomicNumber: 4,
        symbol: 'Be',
        relativeMass: 9.012182,
        protons: 4,
        neutrons: 5,
        electrons: 4,
    },
    {
        name: 'Boron',
        color: '#7d5353',
        atomicNumber: 5,
        symbol: 'B',
        relativeMass: 10.811,
        protons: 5,
        neutrons: 6,
        electrons: 5,
    },
    {
        name: 'Carbon',
        color: '#3b3b3b',
        atomicNumber: 6,
        symbol: 'C',
        relativeMass: 12.0107,
        protons: 6,
        neutrons: 7,
        electrons: 6,
    },
    {
        name: 'Nitrogen',
        color: '#2cc6b2',
        atomicNumber: 7,
        symbol: 'N',
        relativeMass: 14.0067,
        protons: 7,
        neutrons: 8,
        electrons: 7,
    },
    {
        name: 'Oxygen',
        color: '#6fec98',
        atomicNumber: 8,
        symbol: 'O',
        relativeMass: 15.9994,
        protons: 8,
        neutrons: 9,
        electrons: 8,
    },
    {
        name: 'Fluorine',
        color: '#ecc46f',
        atomicNumber: 9,
        symbol: 'F',
        relativeMass: 18.9984032,
        protons: 9,
        neutrons: 10,
        electrons: 9,
    },
    {
        name: 'Neon',
        color: '#be0086',
        atomicNumber: 10,
        symbol: 'Ne',
        relativeMass: 20.1797,
        protons: 10,
        neutrons: 11,
        electrons: 10,
    },
    {
        name: 'Sodium',
        color: '#e69d7a',
        atomicNumber: 11,
        symbol: 'Na',
        relativeMass: 22.98976928,
        protons: 11,
        neutrons: 12,
        electrons: 11,
    },
        {
        name: 'Magnesium',
        color: '#9e80ea',
        atomicNumber: 12,
        symbol: 'Mg',
        relativeMass: 24.305,
        protons: 12,
        neutrons: 13,
        electrons: 12,
    },
    {
        name: 'Aluminum',
        color: '#797979',
        atomicNumber: 13,
        symbol: 'Al',
        relativeMass: 26.9815386,
        protons: 13,
        neutrons: 14,
        electrons: 13,
    },
    {
        name: 'Silicon',
        color: '#4a4070',
        atomicNumber: 14,
        symbol: 'Si',
        relativeMass: 28.0855,
        protons: 14,
        neutrons: 15,
        electrons: 14,
    },
    {
        name: 'Phosphorus',
        color: '#d7463f',
        atomicNumber: 15,
        symbol: 'P',
        relativeMass: 30.973762,
        protons: 15,
        neutrons: 16,
        electrons: 15,
    },
    {
        name: 'Sulfur',
        color: '#375e7c',
        atomicNumber: 16,
        symbol: 'S',
        relativeMass: 32.065,
        protons: 16,
        neutrons: 17,
        electrons: 16,
    },
    {
        name: 'Chlorine',
        color: '#6d1d7b',
        atomicNumber: 17,
        symbol: 'Cl',
        relativeMass: 35.453,
        protons: 17,
        neutrons: 18,
        electrons: 17,
    },
    {
        name: 'Argon',
        color: '#9a3da5',
        atomicNumber: 18,
        symbol: 'Ar',
        relativeMass: 39.948,
        protons: 18,
        neutrons: 19,
        electrons: 18,
    },
    {
        name: 'Potassium',
        color: '#4d8946',
        atomicNumber: 19,
        symbol: 'K',
        relativeMass: 39.098,
        protons: 19,
        neutrons: 20,
        electrons: 19,
    },
    {
        name: 'Calcium',
        color: '#f0f0f0',
        atomicNumber: 20,
        symbol: 'Ca',
        relativeMass: 40.078,
        protons: 20,
        neutrons: 21,
        electrons: 20,
    },
    {
        name: 'Scandium',
        color: '#5fbb77',
        atomicNumber: 21,
        symbol: 'Sc',
        relativeMass: 44.956,
        protons: 21,
        neutrons: 22,
        electrons: 21,
    },
    {
        name: 'Titanium',
        color: '#5a5a5a',
        atomicNumber: 22,
        symbol: 'Ti',
        relativeMass: 47.867,
        protons: 22,
        neutrons: 22,
        electrons: 22,
    },
    {
        name: 'Vanadium',
        color: '#5f9ebb',
        atomicNumber: 23,
        symbol: 'V',
        relativeMass: 50.941,
        protons: 23,
        neutrons: 23,
        electrons: 23,
    },
    {
        name: 'Chromium',
        color: '#a488b5',
        atomicNumber: 24,
        symbol: 'Cr',
        relativeMass: 51.996,
        protons: 24,
        neutrons: 24,
        electrons: 24,
    },
    {
        name: 'Manganese',
        color: '#dc4a4a',
        atomicNumber: 25,
        symbol: 'Mn',
        relativeMass: 54.938,
        protons: 25,
        neutrons: 25,
        electrons: 25,
    },
    {
        name: 'Iron',
        color: '#ab967d',
        atomicNumber: 26,
        symbol: 'Fe',
        relativeMass: 55.845,
        protons: 26,
        neutrons: 26,
        electrons: 26,
    },
    {
        name: 'Cobalt',
        color: '#4371e6',
        atomicNumber: 27,
        symbol: 'Co',
        relativeMass: 58.933,
        protons: 27,
        neutrons: 27,
        electrons: 27,
    },
    {
        name: 'Nickel',
        color: '#bac395',
        atomicNumber: 28,
        symbol: 'Ni',
        relativeMass: 58.693,
        protons: 28,
        neutrons: 28,
        electrons: 28,
    },
    {
        name: 'Copper',
        color: '#b95739',
        atomicNumber: 29,
        symbol: 'Cu',
        relativeMass: 63.546,
        protons: 29,
        neutrons: 29,
        electrons: 29,
    },
    {
        name: 'Zinc',
        color: '#b4b4b4',
        atomicNumber: 30,
        symbol: 'Zn',
        relativeMass: 65.38,
        protons: 30,
        neutrons: 30,
        electrons: 30,
    },
    {
        name: 'Gallium',
        color: '#39b975',
        atomicNumber: 31,
        symbol: 'Ga',
        relativeMass: 69.723,
        protons: 31,
        neutrons: 31,
        electrons: 31,
    },
    {
        name: 'Germanium',
        color: '#979273',
        atomicNumber: 32,
        symbol: 'Ge',
        relativeMass: 72.64,
        protons: 32,
        neutrons: 32,
        electrons: 32,
    },
    {
        name: 'Arsenic',
        color: '#738498',
        atomicNumber: 33,
        symbol: 'As',
        relativeMass: 74.922,
        protons: 33,
        neutrons: 33,
        electrons: 33,
    },
    {
        name: 'Selenium',
        color: '#424242',
        atomicNumber: 34,
        symbol: 'Se',
        relativeMass: 78.96,
        protons: 34,
        neutrons: 34,
        electrons: 34,
    },
    {
        name: 'Bromine',
        color: '#d4753c',
        atomicNumber: 35,
        symbol: 'Br',
        relativeMass: 79.904,
        protons: 35,
        neutrons: 35,
        electrons: 35,
    },
    {
        name: 'Krypton',
        color: '#3ca0d4',
        atomicNumber: 36,
        symbol: 'Kr',
        relativeMass: 83.798,
        protons: 36,
        neutrons: 36,
        electrons: 36,
    },
    {
        name: 'Rubidium',
        color: '#e8e8e8',
        atomicNumber: 37,
        symbol: 'Rb',
        relativeMass: 85.468,
        protons: 37,
        neutrons: 37,
        electrons: 37,
    },
    {
        name: 'Strontium',
        color: '#ff9d29',
        atomicNumber: 38,
        symbol: 'Sr',
        relativeMass: 87.62,
        protons: 38,
        neutrons: 38,
        electrons: 38,
    },
    {
        name: 'Yttrium',
        color: '#b129ff',
        atomicNumber: 39,
        symbol: 'Y',
        relativeMass: 88.906,
        protons: 39,
        neutrons: 39,
        electrons: 39,
    },
    {
        name: 'Zirconium',
        color: '#d6e43a',
        atomicNumber: 40,
        symbol: 'Zr',
        relativeMass: 91.224,
        protons: 40,
        neutrons: 40,
        electrons: 40,
    },
    {
        name: 'Niobium',
        color: '#75dceb',
        atomicNumber: 41,
        symbol: 'Nb',
        relativeMass: 92.906,
        protons: 41,
        neutrons: 41,
        electrons: 41,
    },
    {
        name: 'Molybdenum',
        color: '#8ba38c',
        atomicNumber: 42,
        symbol: 'Mo',
        relativeMass: 95.95,
        protons: 42,
        neutrons: 42,
        electrons: 42,
    },
    {
        name: 'Technetium',
        color: '#eea1e2',
        atomicNumber: 43,
        symbol: 'Tc',
        relativeMass: 98,
        protons: 43,
        neutrons: 43,
        electrons: 43,
    },
    {
        name: 'Ruthenium',
        color: '#563e32',
        atomicNumber: 44,
        symbol: 'Ru',
        relativeMass: 101.07,
        protons: 44,
        neutrons: 44,
        electrons: 44,
    },
    {
        name: 'Rhodium',
        color: '#88d17a',
        atomicNumber: 45,
        symbol: 'Rh',
        relativeMass: 102.91,
        protons: 45,
        neutrons: 45,
        electrons: 45,
    },
    {
        name: 'Palladium',
        color: '#9eabbe',
        atomicNumber: 46,
        symbol: 'Pd',
        relativeMass: 106.42,
        protons: 46,
        neutrons: 46,
        electrons: 46,
    },
    {
        name: 'Silver',
        color: '#dcdcdc',
        atomicNumber: 47,
        symbol: 'Ag',
        relativeMass: 107.87,
        protons: 47,
        neutrons: 47,
        electrons: 47,
    },
    {
        name: 'Cadmium',
        color: '#5560c8',
        atomicNumber: 48,
        symbol: 'Cd',
        relativeMass: 112.41,
        protons: 48,
        neutrons: 48,
        electrons: 48,
    },
    {
        name: 'Indium',
        color: '#408d3c',
        atomicNumber: 49,
        symbol: 'In',
        relativeMass: 114.82,
        protons: 49,
        neutrons: 49,
        electrons: 49,
    },
    {
        name: 'Tin',
        color: '#b5a47c',
        atomicNumber: 50,
        symbol: 'Sn',
        relativeMass: 118.71,
        protons: 50,
        neutrons: 50,
        electrons: 50,
    },
    {
        name: 'Antimony',
        color: '#c6598c',
        atomicNumber: 51,
        symbol: 'Sb',
        relativeMass: 121.76,
        protons: 51,
        neutrons: 51,
        electrons: 51,
    },
    {
        name: 'Tellurium',
        color: '#b29cff',
        atomicNumber: 52,
        symbol: 'Te',
        relativeMass: 127.6,
        protons: 52,
        neutrons: 52,
        electrons: 52,
    },
    {
        name: 'Iodine',
        color: '#a8a8a8',
        atomicNumber: 53,
        symbol: 'I',
        relativeMass: 126.9,
        protons: 53,
        neutrons: 53,
        electrons: 53,
    },
    {
        name: 'Xenon',
        color: '#a8a8a8',
        atomicNumber: 54,
        symbol: 'Xe',
        relativeMass: 131.29,
        protons: 54,
        neutrons: 54,
        electrons: 54,
    },
    {
        name: 'Caesium',
        color: '#e8e8e8',
        atomicNumber: 55,
        symbol: 'Cs',
        relativeMass: 132.91,
        protons: 55,
        neutrons: 55,
        electrons: 55,
    },
    {
        name: 'Barium',
        color: '#ff9d29',
        atomicNumber: 56,
        symbol: 'Ba',
        relativeMass: 137.33,
        protons: 56,
        neutrons: 56,
        electrons: 56,
    },
    {
        name: 'Lanthanum',
        color: '#b129ff',
        atomicNumber: 57,
        symbol: 'La',
        relativeMass: 138.91,
        protons: 57,
        neutrons: 57,
        electrons: 57,
    },
    {
        name: 'Cerium',
        color: '#d6e43a',
        atomicNumber: 58,
        symbol: 'Ce',
        relativeMass: 140.12,
        protons: 58,
        neutrons: 58,
        electrons: 58,
    },
    {
        name: 'Praseodymium',
        color: '#75dceb',
        atomicNumber: 59,
        symbol: 'Pr',
        relativeMass: 140.91,
        protons: 59,
        neutrons: 59,
        electrons: 59,
    },
    {
        name: 'Neodymium',
        color: '#8ba38c',
        atomicNumber: 60,
        symbol: 'Nd',
        relativeMass: 144.24,
        protons: 60,
        neutrons: 60,
        electrons: 60,
    },
    {
        name: 'Promethium',
        color: '#eea1e2',
        atomicNumber: 61,
        symbol: 'Pm',
        relativeMass: 145,
        protons: 61,
        neutrons: 61,
        electrons: 61,
    },
    {
        name: 'Samarium',
        color: '#563e32',
        atomicNumber: 62,
        symbol: 'Sm',
        relativeMass: 150.36,
        protons: 62,
        neutrons: 62,
        electrons: 62,
    },
    {
        name: 'Europium',
        color: '#88d17a',
        atomicNumber: 63,
        symbol: 'Eu',
        relativeMass: 151.96,
        protons: 63,
        neutrons: 63,
        electrons: 63,
    },
    {
        name: 'Gadolinium',
        color: '#9eabbe',
        atomicNumber: 64,
        symbol: 'Gd',
        relativeMass: 157.25,
        protons: 64,
        neutrons: 64,
        electrons: 64,
    },
    {
        name: 'Terbium',
        color: '#eea1e2',
        atomicNumber: 65,
        symbol: 'Tb',
        relativeMass: 158.93,
        protons: 65,
        neutrons: 65,
        electrons: 65,
    },
    {
        name: 'Dysprosium',
        color: '#dcdcdc',
        atomicNumber: 66,
        symbol: 'Dy',
        relativeMass: 162.5,
        protons: 66,
        neutrons: 66,
        electrons: 66,
    },
    {
        name: 'Holmium',
        color: '#5560c8',
        atomicNumber: 67,
        symbol: 'Ho',
        relativeMass: 164.93,
        protons: 67,
        neutrons: 67,
        electrons: 67,
    },
    {
        name: 'Erbium',
        color: '#408d3c',
        atomicNumber: 68,
        symbol: 'Er',
        relativeMass: 167.26,
        protons: 68,
        neutrons: 68,
        electrons: 68,
    },
    {
        name: 'Thulium',
        color: '#b5a47c',
        atomicNumber: 69,
        symbol: 'Tm',
        relativeMass: 168.93,
        protons: 69,
        neutrons: 69,
        electrons: 69,
    },
    {
        name: 'Ytterbium',
        color: '#c6598c',
        atomicNumber: 70,
        symbol: 'Yb',
        relativeMass: 173.04,
        protons: 70,
        neutrons: 70,
        electrons: 70,
    },
    {
        name: 'Lutetium',
        color: '#b29cff',
        atomicNumber: 71,
        symbol: 'Lu',
        relativeMass: 174.97,
        protons: 71,
        neutrons: 71,
        electrons: 71,
    },
    {
        name: 'Hafnium',
        color: '#a8a8a8',
        atomicNumber: 72,
        symbol: 'Hf',
        relativeMass: 178.49,
        protons: 72,
        neutrons: 72,
        electrons: 72,
    },
    {
        name: 'Tantalum',
        color: '#e8e8e8',
        atomicNumber: 73,
        symbol: 'Ta',
        relativeMass: 180.95,
        protons: 73,
        neutrons: 73,
        electrons: 73,
    },
    {
        name: 'Tungsten',
        color: '#ff9d29',
        atomicNumber: 74,
        symbol: 'W',
        relativeMass: 183.84,
        protons: 74,
        neutrons: 74,
        electrons: 74,
    },
    {
        name: 'Rhenium',
        color: '#b129ff',
        atomicNumber: 75,
        symbol: 'Re',
        relativeMass: 186.21,
        protons: 75,
        neutrons: 75,
        electrons: 75,
    },
    {
        name: 'Osmium',
        color: '#d6e43a',
        atomicNumber: 76,
        symbol: 'Os',
        relativeMass: 190.23,
        protons: 76,
        neutrons: 76,
        electrons: 76,
    },
    {
        name: 'Iridium',
        color: '#75dceb',
        atomicNumber: 77,
        symbol: 'Ir',
        relativeMass: 192.22,
        protons: 77,
        neutrons: 77,
        electrons: 77,
    },
    {
        name: 'Platinum',
        color: '#8ba38c',
        atomicNumber: 78,
        symbol: 'Pt',
        relativeMass: 195.08,
        protons: 78,
        neutrons: 78,
        electrons: 78,
    },
    {
        name: 'Gold',
        color: '#eea1e2',
        atomicNumber: 79,
        symbol: 'Au',
        relativeMass: 196.97,
        protons: 79,
        neutrons: 79,
        electrons: 79,
    },
    {
        name: 'Mercury',
        color: '#563e32',
        atomicNumber: 80,
        symbol: 'Hg',
        relativeMass: 200.59,
        protons: 80,
        neutrons: 80,
        electrons: 80,
    },
    {
        name: 'Thallium',
        color: '#88d17a',
        atomicNumber: 81,
        symbol: 'Tl',
        relativeMass: 204.38,
        protons: 81,
        neutrons: 81,
        electrons: 81,
    },
    {
        name: 'Lead',
        color: '#9eabbe',
        atomicNumber: 82,
        symbol: 'Pb',
        relativeMass: 207.2,
        protons: 82,
        neutrons: 82,
        electrons: 82,
    },
    {
        name: 'Bismuth',
        color: '#eea1e2',
        atomicNumber: 83,
        symbol: 'Bi',
        relativeMass: 208.98,
        protons: 83,
        neutrons: 83,
        electrons: 83,
    },
    {
        name: 'Polonium',
        color: '#dcdcdc',
        atomicNumber: 84,
        symbol: 'Po',
        relativeMass: 209,
        protons: 84,
        neutrons: 84,
        electrons: 84,
    },
    {
        name: 'Astatine',
        color: '#5560c8',
        atomicNumber: 85,
        symbol: 'At',
        relativeMass: 210,
        protons: 85,
        neutrons: 85,
        electrons: 85,
    },
    {
        name: 'Radon',
        color: '#408d3c',
        atomicNumber: 86,
        symbol: 'Rn',
        relativeMass: 222,
        protons: 86,
        neutrons: 86,
        electrons: 86,
    },
    {
        name: 'Francium',
        color: '#b5a47c',
        atomicNumber: 87,
        symbol: 'Fr',
        relativeMass: 223,
        protons: 87,
        neutrons: 87,
        electrons: 87,
    },
    {
        name: 'Radium',
        color: '#c6598c',
        atomicNumber: 88,
        symbol: 'Ra',
        relativeMass: 226,
        protons: 88,
        neutrons: 88,
        electrons: 88,
    },
    {
        name: 'Actinium',
        color: '#b29cff',
        atomicNumber: 89,
        symbol: 'Ac',
        relativeMass: 227,
        protons: 89,
        neutrons: 89,
        electrons: 89,
    },
    {
        name: 'Thorium',
        color: '#a8a8a8',
        atomicNumber: 90,
        symbol: 'Th',
        relativeMass: 232.03,
        protons: 90,
        neutrons: 90,
        electrons: 90,
    },
    {
        name: 'Protactinium',
        color: '#e8e8e8',
        atomicNumber: 91,
        symbol: 'Pa',
        relativeMass: 231.04,
        protons: 91,
        neutrons: 91,
        electrons: 91,
    },
    {
        name: 'Uranium',
        color: '#ff9d29',
        atomicNumber: 92,
        symbol: 'U',
        relativeMass: 238.03,
        protons: 92,
        neutrons: 92,
        electrons: 92,
    },
    {
        name: 'Neptunium',
        color: '#b129ff',
        atomicNumber: 93,
        symbol: 'Np',
        relativeMass: 237,
        protons: 93,
        neutrons: 93,
        electrons: 93,
    },
    {
        name: 'Plutonium',
        color: '#d6e43a',
        atomicNumber: 94,
        symbol: 'Pu',
        relativeMass: 244,
        protons: 94,
        neutrons: 94,
        electrons: 94,
    },
    {
        name: 'Americium',
        color: '#75dceb',
        atomicNumber: 95,
        symbol: 'Am',
        relativeMass: 243,
        protons: 95,
        neutrons: 95,
        electrons: 95,
    },
    {
        name: 'Curium',
        color: '#8ba38c',
        atomicNumber: 96,
        symbol: 'Cm',
        relativeMass: 247,
        protons: 96,
        neutrons: 96,
        electrons: 96,
    },
    {
        name: 'Berkelium',
        color: '#eea1e2',
        atomicNumber: 97,
        symbol: 'Bk',
        relativeMass: 247,
        protons: 97,
        neutrons: 97,
        electrons: 97,
    },
    {
        name: 'Californium',
        color: '#563e32',
        atomicNumber: 98,
        symbol: 'Cf',
        relativeMass: 251,
        protons: 98,
        neutrons: 98,
        electrons: 98,
    },
    {
        name: 'Einsteinium',
        color: '#88d17a',
        atomicNumber: 99,
        symbol: 'Es',
        relativeMass: 252,
        protons: 99,
        neutrons: 99,
        electrons: 99,
    },
    {
        name: 'Fermium',
        color: '#9eabbe',
        atomicNumber: 100,
        symbol: 'Fm',
        relativeMass: 257,
        protons: 100,
        neutrons: 100,
        electrons: 100,
    },
    {
        name: 'Mendelevium',
        color: '#eea1e2',
        atomicNumber: 101,
        symbol: 'Md',
        relativeMass: 258,
        protons: 101,
        neutrons: 101,
        electrons: 101,
    },
    {
        name: 'Nobelium',
        color: '#dcdcdc',
        atomicNumber: 102,
        symbol: 'No',
        relativeMass: 259,
        protons: 102,
        neutrons: 102,
        electrons: 102,
    },
    {
        name: 'Lawrencium',
        color: '#5560c8',
        atomicNumber: 103,
        symbol: 'Lr',
        relativeMass: 262,
        protons: 103,
        neutrons: 103,
        electrons: 103,
    },
    {
        name: 'Rutherfordium',
        color: '#408d3c',
        atomicNumber: 104,
        symbol: 'Rf',
        relativeMass: 261,
        protons: 104,
        neutrons: 104,
        electrons: 104,
    },
    {
        name: 'Dubnium',
        color: '#b5a47c',
        atomicNumber: 105,
        symbol: 'Db',
        relativeMass: 262,
        protons: 105,
        neutrons: 105,
        electrons: 105,
    },
    {
        name: 'Seaborgium',
        color: '#c6598c',
        atomicNumber: 106,
        symbol: 'Sg',
        relativeMass: 266,
        protons: 106,
        neutrons: 106,
        electrons: 106,
    },
    {
        name: 'Bohrium',
        color: '#b29cff',
        atomicNumber: 107,
        symbol: 'Bh',
        relativeMass: 264,
        protons: 107,
        neutrons: 107,
        electrons: 107,
    },
    {
        name: 'Hassium',
        color: '#a8a8a8',
        atomicNumber: 108,
        symbol: 'Hs',
        relativeMass: 269,
        protons: 108,
        neutrons: 108,
        electrons: 108,
    },
    {
        name: 'Meitnerium',
        color: '#e8e8e8',
        atomicNumber: 109,
        symbol: 'Mt',
        relativeMass: 268,
        protons: 109,
        neutrons: 109,
        electrons: 109,
    },
    {
        name: 'Darmstadtium',
        color: '#ff9d29',
        atomicNumber: 110,
        symbol: 'Ds',
        relativeMass: 271,
        protons: 110,
        neutrons: 110,
        electrons: 110,
    },
    {
        name: 'Roentgenium',
        color: '#b129ff',
        atomicNumber: 111,
        symbol: 'Rg',
        relativeMass: 272,
        protons: 111,
        neutrons: 111,
        electrons: 111,
    },
    {
        name: 'Copernicium',
        color: '#d6e43a',
        atomicNumber: 112,
        symbol: 'Cn',
        relativeMass: 285,
        protons: 112,
        neutrons: 112,
        electrons: 112,
    },
    // overflow the number of electrons in eletronic shells
    // {
    //     name: 'Ununtrium',
    //     color: '#75dceb',
    //     atomicNumber: 113,
    //     symbol: 'Uut',
    //     relativeMass: 284,
    //     protons: 113,
    //     neutrons: 113,
    //     electrons: 113,
    // },
    // {
    //     name: 'Flerovium',
    //     color: '#8ba38c',
    //     atomicNumber: 114,
    //     symbol: 'Fl',
    //     relativeMass: 289,
    //     protons: 114,
    //     neutrons: 114,
    //     electrons: 114,
    // },
    // {
    //     name: 'Ununpentium',
    //     color: '#eea1e2',
    //     atomicNumber: 115,
    //     symbol: 'Uup',
    //     relativeMass: 288,
    //     protons: 115,
    //     neutrons: 115,
    //     electrons: 115,
    // },
    // {
    //     name: 'Livermorium',
    //     color: '#563e32',
    //     atomicNumber: 116,
    //     symbol: 'Lv',
    //     relativeMass: 293,
    //     protons: 116,
    //     neutrons: 116,
    //     electrons: 116,
    // },
    // {
    //     name: 'Ununseptium',
    //     color: '#88d17a',
    //     atomicNumber: 117,
    //     symbol: 'Uus',
    //     relativeMass: 294,
    //     protons: 117,
    //     neutrons: 117,
    //     electrons: 117,
    // },
    // {
    //     name: 'Ununoctium',
    //     color: '#9eabbe',
    //     atomicNumber: 118,
    //     symbol: 'Uuo',
    //     relativeMass: 294,
    //     protons: 118,
    //     neutrons: 118,
    //     electrons: 118,
    // },
];